name: AiNiee Beta Build.
on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Build Rust Updater
        shell: cmd
        run: |
          cd rust_updater
          cargo build --release --package updater
      
      # 可以减少rust更新器和python可执行文件大小
      - name: Install UPX
        shell: cmd
        run: |
          choco install upx -y
      
      - name: Compress Rust Binaries
        shell: cmd
        run: |
          upx --best --lzma .\rust_updater\target\release\updater.exe

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install -r requirements.txt
          python -m pip cache purge

      - name: Build EXE
        run: python .\Tools\pyinstall.py

      - name: Pack Resource
        run: |
          Copy-Item -Path "Resource" -Destination "dist\Resource" -Recurse -Force
          Copy-Item -Path "StevExtraction" -Destination "dist\StevExtraction" -Recurse -Force
          Copy-Item -Path "PluginScripts" -Destination "dist\PluginScripts" -Recurse -Force
          Copy-Item -Path ".\rust_updater\target\release\updater.exe" -Destination "dist\updater.exe" -Force
          Copy-Item -path "Version" -Destination "dist\Version" -Force
          Compress-Archive -Path "dist" -DestinationPath "AiNiee-Beta.zip"

      - name: Delete release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: Beta
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Beta
          name: AiNiee-Beta 开发测试版本，由最新源码自动打包
          body: AiNiee-Beta 开发测试版本，由最新源码自动打包
          draft: false
          prerelease: true
          files: AiNiee-Beta.zip
